apiVersion: v1
kind: ConfigMap
metadata:
  name: tracking-config
data:
 config: |
  <?php
    define("DB_HOST", getenv("DB_HOST"));
    define("DB_USER", getenv("DB_USER"));
    define("DB_PASS", getenv("DB_PASS"));
    define("DB_NAME", getenv("DB_NAME"));
    define("FRAMEWORK", "/var/www/track/public/app/");
    define('APPROOT', dirname(dirname(__FILE__)));
    define('URLROOT', 'https://tracking.franslourens.co.za');
    define('SITENAME', 'Track');
--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: tracking-tests
data:
 config: |
  <?php
    define("DB_HOST", getenv("DB_HOST"));
    define("DB_USER", getenv("DB_USER"));
    define("DB_PASS", getenv("DB_PASS"));
    define("DB_NAME", getenv("DB_NAME"));
    require_once(FRAMEWORK . "libraries/iModel.php");
    require_once(FRAMEWORK . "libraries/BaseModel.php");
    require_once(FRAMEWORK . "libraries/Database.php");
--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: tracking-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      component: tracking-web
  template: 
    metadata: 
      labels: 
        component: tracking-web
    spec: 
      initContainers:
        - args:
            - /bin/bash
            - -c
            - (chown -R app:www-data /app/ && cp -rp /app/* /var/www/track/public/)
              && mkdir /var/www/track/public/app/config/
              && cp /etc/config/env /var/www/track/public/app/config/development.php 
              && (chown -R app:www-data /var/www/)
          image: frans86/php-tracking
          name: tracking
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: postgreshost 
                  key: postgreshost 
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgresuser 
                  key: postgresuser 
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgresspass 
                  key: postgresspass 
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgresname 
                  key: postgresname 
          volumeMounts:
            - 
              name: code
              mountPath: /var/www/track/public
            - name: config-volume
              mountPath: /etc/config      
      containers: 
        - 
          image: frans86/nginx-tracking
          imagePullPolicy: Always
          name: nginx
          ports: 
            - 
              containerPort: 80
          volumeMounts: 
            - 
              mountPath: /var/www/track/public
              name: code
            - 
              mountPath: /socket
              name: sock
        - 
          image: frans86/php-tracking
          imagePullPolicy: Always
          name: fpm
          volumeMounts: 
            - 
              mountPath: /var/www/track/public
              name: code
            - 
              mountPath: /socket
              name: sock
            - 
              mountPath: /etc/config
              name: config-volume
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: postgreshost 
                  key: postgreshost 
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgresuser 
                  key: postgresuser 
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgresspass 
                  key: postgresspass 
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgresname 
                  key: postgresname 
      volumes: 
        - 
          emptyDir: {}
          name: code
        - 
          emptyDir: {}
          name: sock
        - 
          configMap: 
            items: 
              - 
                key: config
                path: env
            name: tracking-config
          name: config-volume
